version: "3.9"

services:
  dtl:
    container_name: boba_dtl
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.data-transport-layer
    env_file:
      -  ./envs/dtl.env
    environment:
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: 'https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_KEY}'
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: https://lightning-replica.boba.network
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: 'false'
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'true'
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 288
      DATA_TRANSPORT_LAYER__ETH1_CTC_DEPLOYMENT_HEIGHT: 13502893
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: 10000
      DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: '0x8376ac6C3f73a25Dd994E0b0669ca7ee0C02F089'
      DATA_TRANSPORT_LAYER__BSS_HARDFORK_1_INDEX: 381145
      DATA_TRANSPORT_LAYER__TURING_V0_HEIGHT: 381145
      DATA_TRANSPORT_LAYER__TURING_V1_HEIGHT: 381145
    volumes:
      - ./:/opt/optimism/packages/data-transport-layer/state-dumps/
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - "127.0.01:${DTL_PORT:-32878}:7878"
      - "127.0.01:${REGISTRY_PORT:-32080}:8081"

  replica:
    container_name: boba_replica
    depends_on:
      - dtl
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.geth
    deploy:
      replicas: 1
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    volumes:
      - /opt/nodes/boba/data/geth:/root/.ethereum/
    environment:
      ETH1_HTTP: 'https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_KEY}'
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://dtl:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'true'
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
      BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
      ROLLUP_POLL_INTERVAL_FLAG: "10s"
      ROLLUP_ENFORCE_FEES: 'true'
      SEQUENCER_CLIENT_HTTP: https://mainnet.boba.network
      # turing
      TURING_CREDIT_ADDRESS: "0xF8D2f1b0292C0Eeef80D8F47661A9DaCDB4b23bf"
      # fee token
      L2_BOBA_TOKEN_ADDRESS: "0xa18bF3994C0Cc6E3b63ac420308E5383f53120D7"
      BOBA_GAS_PRICE_ORACLE_ADDRESS: "0xeE06ee2F239d2ab11792D77f3C347d919ddA0d51"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - "127.0.01:${L2GETH_HTTP_PORT:-32549}:8545"
      - "127.0.01:${L2GETH_WS_PORT:-32550}:8546"
